### ISSUE TITLE
[aesthetics] - misalign button find a property

### ISSUE THREAD

**Issue by ghost** [anthonyteoxon/ipostmo-testing#2]
Actual Result:
- misalign button find a property
  ![screen shot 2015-10-01 at 5 10 36 am](https://cloud.githubusercontent.com/assets/711991/10206819/8f5f5b8e-67fb-11e5-971a-10ca0d977692.png)

Expected Result:
- Correct UI positioning/alignment

**Comment by reyiguin** [comment]
this issue was fix
![button alignment](https://cloud.githubusercontent.com/assets/14901947/10216335/d47f7e38-685a-11e5-985d-beadd6e2b521.png)

**Comment by ghost** [comment]
Please close this issue

**Comment by reyiguin** [comment]
sir kayo po magcclose nto or kung cnu ung nagpost. d po ksi namin mclose wla ung button for close issue. thanks

**Comment by anthonyteoxon** [comment]
closed.
