### ISSUE TITLE
[aesthetics] - blank space on front page

### ISSUE THREAD

**Issue by ghost** [anthonyteoxon/ipostmo-testing#3]
Actual Result: 
![screen shot 2015-10-01 at 5 17 53 am](https://cloud.githubusercontent.com/assets/711991/10206958/3e692218-67fc-11e5-8ae0-acca58e687c3.png)

Expected Result:
- Need to add content or remove it

**Comment by jmong143** [comment]
sir we added the recent post in the main page of ipostmo.com

![recent post1](https://cloud.githubusercontent.com/assets/13063423/10240097/1537c70a-690a-11e5-943b-509bf7fd5efd.jpg)
![recent post2](https://cloud.githubusercontent.com/assets/13063423/10240096/14b8ffce-690a-11e5-8af0-a7c63abc9d92.jpg)
