### ISSUE TITLE
[aesthetics] - text color mismatch

### ISSUE THREAD

**Issue by ghost** [anthonyteoxon/ipostmo-testing#4]
Actual Result:
![screen shot 2015-10-01 at 5 27 47 am](https://cloud.githubusercontent.com/assets/711991/10207160/4d0d1300-67fd-11e5-822b-9175f6eb0f61.png)

Expected Result:
- Note: Do not use light text color on the light background or vice versa with the dark.

Suggest Result:
![screen shot 2015-10-01 at 5 23 27 am](https://cloud.githubusercontent.com/assets/711991/10207158/499cd02a-67fd-11e5-87ec-f1f618ef3ea7.png)

**Comment by reyiguin** [comment]
this issue was fix
![text mismatch](https://cloud.githubusercontent.com/assets/14901947/10216276/59439448-685a-11e5-88de-48d2433bd38f.png)

**Comment by ghost** [comment]
Nice one

**Comment by anthonyteoxon** [comment]
closed.
