### ISSUE TITLE
[Error Spiels] - Not handle validation

### ISSUE THREAD

**Issue by ghost** [anthonyteoxon/ipostmo-testing#6]
Steps to replicate:
1. On My profile page, follow this step #5 
2. Re-enter your desired display name, profile type and about you
3. Then, click Save

Actual Result:
![screen shot 2015-10-01 at 5 46 38 am](https://cloud.githubusercontent.com/assets/711991/10208291/f0250faa-6804-11e5-8760-982deaeea440.png)

Expected Result:
- Successful saving my three (3) content data such as display name, profile type and about you.

**Comment by anthonyteoxon** [comment]
![screen shot 2015-10-01 at 6 46 07 pm](https://cloud.githubusercontent.com/assets/3824350/10219229/ac35c58a-686f-11e5-9370-0d6f7a70fd10.png)

now not requiring any fields in profile settings. If User's display name is empty then it would show the full name as the default display name.
