### ISSUE TITLE
[aesthetics] - Forgot Password

### ISSUE THREAD

**Issue by stepheljobs** [anthonyteoxon/ipostmo-testing#7]
Scenarios:
None.

Actual Result:
![screen shot 2015-10-01 at 6 22 04 am](https://cloud.githubusercontent.com/assets/8773383/10208603/0f9585f2-6807-11e5-8ef7-fcec39d8e04c.png)

Suggested Result:
Can we put down the forgot password button aligned with "Remember me?" or Under the "Don't Have an account? Register Now!"?

**Comment by reyiguin** [comment]
this issue was fix.
![forgot password](https://cloud.githubusercontent.com/assets/14901947/10216041/d79bd2c6-6858-11e5-9427-01f990dadf4a.png)

**Comment by reyiguin** [comment]
updated forgot password
![forgot password](https://cloud.githubusercontent.com/assets/14901947/10218955/8777efcc-686d-11e5-9930-e581c2a44d75.png)

**Comment by anthonyteoxon** [comment]
Much better. ticket will be closed.
