### ISSUE TITLE
[contact-settings] - no identifier if required or not with the specific data entry

### ISSUE THREAD

**Issue by ghost** [anthonyteoxon/ipostmo-testing#9]
Actual Results:
- can't save one (1) or more selected content at a time.
  ![screen shot 2015-10-01 at 12 57 34 pm](https://cloud.githubusercontent.com/assets/711991/10213649/785380ea-6842-11e5-9ba2-42adcb21eea9.png)

Expected Results:
- User can same any field if they wanted, but we impose

**Comment by anthonyteoxon** [comment]
![screen shot 2015-10-01 at 7 04 22 pm](https://cloud.githubusercontent.com/assets/3824350/10219182/489f06bc-686f-11e5-8306-13da7cc455cb.png)

 Now removed the validation for those required fields.
